updated agent to bot and changed code to match requirements
LimeChain/forta-bots pull request #26
Opened 2022-05-10 08:31 UTC by Tdrachev

Updated code to match haseeb's suggestions

2022-05-10 12:32 UTC, dikel approved these changes
LGTM

2022-05-14 12:19 UTC, haseebrabbani commented on forta-agents-linked/src/agent.js
> +      if (name == "AgentUpdated") {
i think we'll need to check for creation only here (not updates). when a bot is updated, the assigned scan node does not change

2022-05-14 12:21 UTC, haseebrabbani commented on forta-agents-linked/src/agent.js
> +        aboveThreshold = timeHandler.checkIfPassedThreshold();
we're only checking if the threshold is passed for Link events, but what if the Link event never fires? we would want to be alerted about this case i.e. agent is created, but does not get linked for longer than threshold

2022-05-16 09:10 UTC, stoqnkpL requested changes
Did we resolve this comment?
```
we're only checking if the threshold is passed for Link events, but what if the Link event never fires? we would want to be alerted about this case i.e. agent is created, but does not get linked for longer than threshold
```

2022-05-16 09:10 UTC, stoqnkpL commented on forta-agents-linked/README.md
> +Detects if a FORTA Bot has been linked over 5 minutes after being updated
```suggestion
Detects if a FORTA Bot has not been linked over 5 minutes after being created
```

2022-05-16 09:10 UTC, stoqnkpL commented on forta-agents-linked/package.json
> +  "description": "Detects if a FORTA Bot has been linked over 5 minutes after being updated",
```suggestion
  "description": "Detects if a FORTA Bot has not been linked over 5 minutes after being created",
```

2022-05-16 09:10 UTC, stoqnkpL commented on forta-agents-linked/src/TimeHandler.js
> +  addToListUpdated(address) {
`addToListCreated` or `addToCreatedBotsList`

2022-05-16 10:22 UTC, stoqnkpL approved these changes
LGTM!

2022-05-16 10:22 UTC, merged